### ISSUE TITLE
POS field refers to different linear references

### ISSUE THREAD

**Issue by leoisl** [iqbal-lab-org/jVCF-spec#2]
`POS` field for sites inside a Lvl-1 site refer to different linear references. It depends on the haplogroup reference for each site, which can be different even if they are in the same Lvl-1 site. For example, in the graph below:

![image](https://user-images.githubusercontent.com/8397967/99691192-db65e280-2a80-11eb-9232-0135afc86a29.png)

 the 4 most inner sites (2, 3, 5, 6) will all have the same `POS` value (3), but these POS, although have the same value, refer to different linear references:
* site 2: ref = TAA
* site 3: ref = TTC
* site 5: ref = CCA
* site 6: ref = CGC

This might be confusing or not... it needs a careful thought if this should be changed or not. Whenever we think about `POS` as defined here, it is with respect to a linear reference (path) in the graph. I think it is more natural or easier to understand if all sites have a `POS` with respect to a single fixed linear reference. With a single fixed linear reference, we have a reference to transform `jVCFs` into `VCF` and then `POS` of the sites of `jVCF` == `POS` of the site of the VCF. A single linear reference, however, give us a representation problem (see Figure 3 of pandora paper). Having several linear references, as is done now, completely minimises the representation problem, but it also means that we might have several linear references for a single graph, which makes it hard to compare `POS` between different sites.

**Comment by bricoletc** [comment]
That's a great explanation of what `POS` is- however, the intention here **is** to have `POS` have a different meaning on different haplogroups! Ie, to have multiple references.

**Comment by leoisl** [comment]
Ok! That makes sense, I would just suggest to emphasise this on the spec, maybe with an example. If I am not mistaken, me, @martinghunt and @iqbal-lab all thought that `POS` was WRT a single chosen reference path. I think this is the most natural and straightforward way of thinking also, as usually when we think about describing graph variants WRT a path in the graph, we usually think of a single reference path that will be used as the VCF reference. However, I do think that the definition of `POS` on multiple references is fine for the jVCF format, I am not proposing any changes. I am just proposing a clarification in the spec, as I think most readers will assume a single chosen reference path, as the 3 of us did.

**Comment by leoisl** [comment]
Ah, for a better understanding, could you please explain the rationale behind `POS`? I've never read the VCF specification, but I guess the idea of `POS` there is to give a coordinate system to be able to compare the position of different calls? So if we have a single chromosome, all VCF records will have `POS` WRT this chromosome, and we are able to compare their positions. For jVCF, however, even inside a single Lvl1 site, the variants' `POS` are not comparable as they might refer to different refs. I think understanding what concept we want to represent with `POS` will make my understanding better! Sorry for keep asking questions on this...

**Comment by iqbal-lab** [comment]
The idea is to be able to position variants with respect to multiple refs. some things fundamentally can't be put on one ref

**Comment by leoisl** [comment]
Ok! Sorry that this was hard for me to understand, but now everything makes sense!
